### ISSUE TITLE
MVC - Criar Telas para Adicionar/Editar/Excluir Padrinho/Doador - CRUD Completo

### ISSUE THREAD

**Issue by Saracvidal** [ICEI-PUC-Minas-PMV-SI/SI_AppSust_2o2023_Grp05#19]

**Comment by isabelamartinez** [comment]
@JPMaiadeP João, como mandei no grupo do WhatsApp hoje mais cedo, sugeri uma proposta diferente pra desenvolver a parte de Usuários / Padrinhos / Doadores, e isso muda as telas dessas 3 coisas. Você já começou a desenvolver esse CRUD?

**Comment by isabelamartinez** [comment]
Minha sugestão é a seguinte:

1. Tela com Lista de Doadores e Padrinhos:

![Image](https://github.com/ICEI-PUC-Minas-PMV-SI/SI_AppSust_2o2023_Grp05/assets/116018324/e6f173f1-22c9-496a-ab63-0c7a2878e164)

Talvez usando o Bootstrap para fazer a lista, então pode ser que a versão final não fique exatamente como a desse mock-up...
Os 3 ícones de lápis na última coluna seriam, na verdade, um ícone para visualizar (um olho), um para editar (lápis) e um para excluir (lixeira, ou x). Passando o mouse sobre ele, a função do ícone aparecerá escrita. 

2. Ao clicar no ícone Visualizar, o usuário é levado a esta tela:

![Image](https://github.com/ICEI-PUC-Minas-PMV-SI/SI_AppSust_2o2023_Grp05/assets/116018324/37234940-ca83-4a98-a60a-b7dec53fac59)

3. Clicando no botão Editar ou no ícone de Lápis da tela anterior (Lista), abre esta tela:

![Image](https://github.com/ICEI-PUC-Minas-PMV-SI/SI_AppSust_2o2023_Grp05/assets/116018324/cb1a026c-3a60-4a31-aef2-3f1f15740685)

4. Para confirmar se o Usuário deseja excluir o registro de Doador/Padrinho, ao clicar no botão Excluir em qualquer página ou no ícone de lixeira/x, ele vê este modal:

![Image](https://github.com/ICEI-PUC-Minas-PMV-SI/SI_AppSust_2o2023_Grp05/assets/116018324/a6997a15-c10b-43e0-b2a1-481804fa5745)

Todos os designs estão no Figma: https://www.figma.com/file/vUda7b8JPpE4NmkcfmTnIz/PetFriends?type=design&node-id=0-1&mode=design&t=rnACxDA4CURHEGOs-0 dentro do retângulo vermelho. @JPMaiadeP

**Comment by Saracvidal** [comment]
Essa tela nao foi o que concordamos no inicio e mesmo assim a pessoa responsavel quis fazer de forma desordenada outra coisa q n foi o que combinamos. Portanto, apos entender por si mesma q essa tela era invalida.
